ci: Install autoconf/libtool on macOS build action
macOS build fails with:

   error: Libtool library used but 'LIBTOOL' is undefined

   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
   to 'configure.ac' and run 'aclocal' and 'autoconf' again.

   If 'LT_INIT' is in 'configure.ac', make sure
   its definition is in aclocal's search path.

Fix it by installing the required dependencies.